# Generated by Django 4.1.3 on 2023-04-10 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recordatorios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(max_length=50)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_finalizacion', models.DateTimeField()),
                ('fecha_creacion', models.DateTimeField()),
                ('estado', models.TextField(max_length=50)),
                ('id_notas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='notas.notas')),
            ],
        ),
    ]
